### ISSUE TITLE
All elements are allowed in ext:news content_elements field

### ISSUE THREAD

**Issue by CIMEOS** [IchHabRecht/content_defender#162]
Hello, 

We have a v12 instance where ext:news is installed.
We would like to manage allowed tt_content when creating a new tt_content from the ext:news `content_elements` field, using the BackendLayout configuration that handles rights by colpos.

For now we see that, even if the colpos is 0 as a default, all tt_contents are allowed in the `type` select. It also allows "hidden" tt_content that are not allowed in BackendLayout configuration of the page where we create this item. 
BackendLayout config does in fact restrict allowed content when creating a new tt_content on the page and in the wizard.

For exemple, all the `news` items should not be allowed on the BackendLayout of the page, and the colpos 0.
I don't think this is a colpos problem since all elements are still available even after submitting the tt_content and registering the colpos.
![image](https://github.com/user-attachments/assets/e09fec80-ad9e-420b-bac6-27b1bd635b85)

**Other solution**
We could use the `TCEFORM.tt_content.CType.removeItems` but this would make us define allowed configuration in multiple places and we would also need to set as many conditions as BackendLayouts/colpos/site. Not the preferred way :) .

Thank you for your time.

**Comment by IchHabRecht** [comment]
Hi @CIMEOS 

as the content elements of EXT:news are provided as inline records, it's unfortunately out of scope of content defender to control the elements.

**Comment by CIMEOS** [comment]
Thank you for your fast anwser, we'll look out for other solutions !

**Comment by lorenzulrich** [comment]
@CIMEOS Did you find another solution, such as using any hooks/events to achieve this?

**Comment by Cameros-agency** [comment]
Hey @lorenzulrich 
Not really, but we managed to limit displayed content elements with TSconfig directly:
```
[1234 in tree.rootLineIds && request && traverse(request.getParsedBody(), 'ajax') > 0 && like(request.getParsedBody()['ajax'][0], "*content_elements-tt_content*")]
    TCEFORM.tt_content.CType.keepItems = textpic
[END]
```
This is working for typo3 v11 and v12 but unfortunately not for v13, `request.getParsedBody()` seems not to be parsed correctly.
We check the name of the IRRE field because we have several in order to simulate columns like pages, but if you only have one then the condition on the pid should be enough and will work with v13.

:warning: Beware of this trick because there is no check on allowed elements like content_defender does, it is just a display limit and can be easily bypassed.
