### ISSUE TITLE
maxitems only works if gridelements is installed

### ISSUE THREAD

**Issue by Skinwalker** [IchHabRecht/content_defender#49]
Versions: 
- TYPO3 8.7.17
- Content Defender 3.0.5

---

As described in the Title I found out that the maxitems setting isn't working if the Extension gridelements isn't installed.

**Comment by IchHabRecht** [comment]
Hi @skinwalker,

I'm sorry, but I can't confirm your issue. Would you mind to share more information about your setup? Thanks for your help.

**Comment by Skinwalker** [comment]
@IchHabRecht 
sure - what do you need.

**Comment by IchHabRecht** [comment]
Hi @Skinwalker,

I need to know:
- your configuration
- what you do in the backend
- what is your expectation
- what occurs instead

Thanks for sharing those information.

**Comment by IchHabRecht** [comment]
Hi @Skinwalker,

Thank you for providing the configuration. First of all: there is no counter or output for maxitems yet, so this is right, that is not supported.

For the maxitems part of your request. I changed `mask_contenthero` to text for testing (as I don't have the mask content element) and I'm able to add one element to the header column. If I try to add another element, I get the expcted error message:
![2018-07-23_170214](https://user-images.githubusercontent.com/1453345/43085104-646836ee-8e9a-11e8-9b02-1d99043e7176.png)
I'm not sure if your issue is coupled to the mask element. Would you mind to try I with a standard core element being allowed, instead? Would you mind to post an image with both elements in the header column?
Thanks for your support.

**Comment by Skinwalker** [comment]
Ahhhhhhh ok ... now i got it ...
The Counter comes from Gridelements, right?

I reinstalled Content Defender and tried to add more than one Content Element - and this time it works!
Don't know what was the problem - maybe the missing counter just confused me :)

+1 for a maxitems counter
